package com.example.querybuilderapi.service;

import com.example.querybuilderapi.model.Notification;
import com.example.querybuilderapi.repository.NotificationRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Service for managing notifications.
 */
@Service
public class NotificationService {

    private final NotificationRepository notificationRepository;

    @Autowired
    public NotificationService(NotificationRepository notificationRepository) {
        this.notificationRepository = notificationRepository;
    }

    /**
     * Creates a new notification.
     */
    @Transactional
    public Notification createNotification(String title, String message, String type) {
        Notification notification = new Notification();
        notification.setTitle(title);
        notification.setMessage(message);
        notification.setType(type);
        notification.setIsRead(false);
        // timestamp is auto-generated by @CreationTimestamp
        return notificationRepository.save(notification);
    }

    /**
     * Retrieves all notifications ordered by newest first.
     */
    public List<Notification> getAllNotifications() {
        return notificationRepository.findAllByOrderByTimestampDesc();
    }

    /**
     * Marks a specific notification as read.
     */
    @Transactional
    public void markAsRead(Long id) {
        notificationRepository.findById(id).ifPresent(notification -> {
            notification.setIsRead(true);
            notificationRepository.save(notification);
        });
    }

    /**
     * Marks all unread notifications as read.
     */
    @Transactional
    public void markAllAsRead() {
        List<Notification> unreadNotifications = notificationRepository.findAll().stream()
                .filter(n -> !n.getIsRead())
                .peek(n -> n.setIsRead(true))
                .collect(Collectors.toList());
        notificationRepository.saveAll(unreadNotifications);
    }

    /**
     * Deletes a specific notification.
     */
    @Transactional
    public void deleteNotification(Long id) {
        notificationRepository.deleteById(id);
    }

    /**
     * Deletes all notifications.
     */
    @Transactional
    public void deleteAllNotifications() {
        notificationRepository.deleteAll();
    }
}
