package com.example.querybuilderapi.service.automation;

import com.example.querybuilderapi.model.Activity;
import com.example.querybuilderapi.model.ActivityType;
import com.example.querybuilderapi.model.EntityType;
import com.example.querybuilderapi.model.Opportunity;
import com.example.querybuilderapi.repository.ActivityRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.Map;

@Component
public class CreateTaskActionExecutor implements ActionExecutor {

    private final ActivityRepository activityRepository;

    public CreateTaskActionExecutor(ActivityRepository activityRepository) {
        this.activityRepository = activityRepository;
    }

    @Override
    @Transactional
    public void execute(Map<String, Object> actionConfig, Object targetEntity) {
        if (!(targetEntity instanceof Opportunity opp)) {
            return;
        }

        String title = (String) actionConfig.getOrDefault("title", "Automated Task");
        String description = (String) actionConfig.getOrDefault("description", "Generated by Automation Rule");

        Activity task = new Activity();
        task.setActivityType(ActivityType.TASK);
        task.setSubject(title);
        task.setBody(description);
        task.setEntityType(EntityType.OPPORTUNITY);
        task.setEntityId(opp.getId());

        activityRepository.save(task);
    }

    @Override
    public String getActionType() {
        return "CREATE_TASK";
    }
}
