package com.example.querybuilderapi.service.automation;

import com.example.querybuilderapi.model.Opportunity;
import com.example.querybuilderapi.service.FcmNotificationService;
import org.springframework.stereotype.Component;

import java.util.Map;

@Component
public class SendFcmActionExecutor implements ActionExecutor {

    private final FcmNotificationService fcmNotificationService;

    public SendFcmActionExecutor(FcmNotificationService fcmNotificationService) {
        this.fcmNotificationService = fcmNotificationService;
    }

    @Override
    public void execute(Map<String, Object> actionConfig, Object targetEntity) {
        String title = (String) actionConfig.getOrDefault("title", "Automated Notification");
        String body = (String) actionConfig.getOrDefault("body", "Notification generated by Automation Rule");
        
        String targetType = (String) actionConfig.getOrDefault("targetType", "TOPIC");
        String targetValue = (String) actionConfig.get("targetValue");

        if (targetValue == null || targetValue.trim().isEmpty()) {
            return;
        }

        if ("TOKEN".equalsIgnoreCase(targetType)) {
            fcmNotificationService.sendToToken(targetValue, title, body, null);
        } else if ("TOPIC".equalsIgnoreCase(targetType)) {
            fcmNotificationService.sendToTopic(targetValue, title, body, null);
        }
    }

    @Override
    public String getActionType() {
        return "SEND_FCM";
    }
}
